import { readFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

/** Repo root, resolved from this file rather than cwd so steps work from anywhere. */
export const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..", "..");

export function fromRoot(...segments) {
  return join(repoRoot, ...segments);
}

export function readRoot(...segments) {
  return readFileSync(fromRoot(...segments), "utf8");
}

/**
 * Comment marker stamped onto generated text files. `pnpm generate:check`
 * catches drift mechanically; this exists so a human who opens the file knows
 * not to edit it before they discover that the hard way.
 */
export function banner(sourceRelPath, syntax = "markdown") {
  const text = `Generated by scripts/generate.mjs from ${sourceRelPath}. Do not edit; edit the source and run \`pnpm generate\`.`;
  return syntax === "markdown" ? `<!-- ${text} -->` : `// ${text}`;
}

/** Everything from a Markdown document's first level-2 heading onward. */
export function bodyFromFirstSection(markdown) {
  const index = markdown.indexOf("\n## ");
  if (index === -1) {
    throw new Error("expected the document to contain at least one level-2 heading");
  }
  return markdown.slice(index + 1);
}
