import { cpSync, existsSync, mkdirSync, mkdtempSync, readFileSync, readdirSync, renameSync, rmSync, statSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";
import { pathToFileURL } from "node:url";

import { SOURCE_METADATA, examplesRoot, fixtureDir, repoRoot, run, snapshotDir, sources } from "./shared.mjs";

/** Repo-relative file list of a tree, sorted, for byte-comparing two snapshots. */
function treeFiles(dir) {
  if (!existsSync(dir)) return [];
  const files = [];
  const walk = (current) => {
    for (const entry of readdirSync(current).sort()) {
      const full = join(current, entry);
      if (statSync(full).isDirectory()) walk(full);
      else files.push(relative(dir, full));
    }
  };
  walk(dir);
  return files.sort();
}

function treesDiffer(a, b) {
  const filesA = treeFiles(a);
  const filesB = treeFiles(b);
  if (filesA.length !== filesB.length || filesA.some((file, index) => file !== filesB[index])) return true;
  return filesA.some((file) => readFileSync(join(a, file), "utf8") !== readFileSync(join(b, file), "utf8"));
}

function renderIndex(entries) {
  return [
    "<!-- Generated by scripts/examples/regenerate.mjs. Do not edit; run `pnpm examples:generate`. -->",
    "",
    "# Examples",
    "",
    "Product maps extracted from pinned, MIT-licensed public repositories. Each directory is exactly what `pmap all` wrote into that repository, so these are reproducible rather than illustrative: `pnpm examples:setup` clones the pinned commits into `fixtures/`, `pnpm examples:generate` rebuilds these snapshots, and `pnpm examples:check` validates them offline.",
    "",
    "Start with `<example>/generated/README.generated.md` — it indexes the rest.",
    "",
    "| Example | Source | Surfaces | Capabilities | Bound |",
    "| ------- | ------ | -------- | ------------ | ----- |",
    ...entries.map(
      (entry) =>
        `| [${entry.name}](${entry.name}/generated/README.generated.md) | [${entry.slug}](https://github.com/${entry.slug}/tree/${entry.commit}) | ${entry.surfaces} | ${entry.capabilities} | ${entry.bound} |`,
    ),
    "",
  ].join("\n");
}

function summarize(dir) {
  const read = (rel) => JSON.parse(readFileSync(join(dir, rel), "utf8"));
  const map = read(join("maps", "map.existing.json"));
  return {
    surfaces: read("surfaces.existing.json").items.length,
    capabilities: read("capabilities.existing.json").items.length,
    bound: map.items.filter((entry) => entry.relationship === "supported").length,
  };
}

/**
 * Rebuilds every snapshot from its pinned checkout.
 *
 * In check mode nothing is written: each snapshot is rebuilt into a staging
 * directory and byte-compared with what is committed. Callers that cannot
 * assume the gitignored checkouts exist pass `requireFixtures: false` and get
 * `{ skipped: true }` instead of an error.
 */
export function regenerateExamples({ check = false, requireFixtures = true } = {}) {
  const missing = sources.filter((source) => !existsSync(join(fixtureDir(source), ".git")));
  if (missing.length > 0) {
    if (!requireFixtures) return { skipped: true, changed: [] };
    throw new Error(
      `missing checkouts for ${missing.map((source) => source.name).join(", ")}; run \`pnpm examples:setup\` first`,
    );
  }

  mkdirSync(examplesRoot, { recursive: true });
  const changed = [];
  const entries = [];

  for (const source of sources) {
    const checkout = fixtureDir(source);
    const head = run("git", ["-C", checkout, "rev-parse", "HEAD"], { stdio: ["ignore", "pipe", "inherit"] }).trim();
    if (head !== source.commit) {
      throw new Error(`${source.name}: checkout is at ${head}; expected ${source.commit}`);
    }

    console.log(`Generating ${source.name}...`);
    run("pnpm", ["exec", "tsx", "packages/pmap/src/cli.ts", "all", "--repo", checkout, "--no-repo-code"], {
      stdio: ["ignore", "pipe", "inherit"],
    });

    // Staged inside examples/ so the swap below is a rename on one filesystem.
    const staged = mkdtempSync(join(examplesRoot, `.tmp-${source.name}-`));
    try {
      cpSync(join(checkout, "docs", "reference", "product-map"), staged, { recursive: true });
      writeFileSync(join(staged, SOURCE_METADATA), `${JSON.stringify(source, null, 2)}\n`);
      entries.push({ ...source, slug: source.repository.replace(/^https:\/\/github\.com\/|\.git$/g, ""), ...summarize(staged) });

      const target = snapshotDir(source);
      if (!treesDiffer(staged, target)) continue;
      changed.push(relative(repoRoot, target));
      if (check) continue;

      const backup = join(examplesRoot, `.previous-${source.name}`);
      rmSync(backup, { recursive: true, force: true });
      if (existsSync(target)) renameSync(target, backup);
      try {
        renameSync(staged, target);
        rmSync(backup, { recursive: true, force: true });
      } catch (error) {
        if (existsSync(backup) && !existsSync(target)) renameSync(backup, target);
        throw error;
      }
    } finally {
      rmSync(staged, { recursive: true, force: true });
    }
  }

  const index = join(examplesRoot, "README.md");
  const content = renderIndex(entries);
  if (!existsSync(index) || readFileSync(index, "utf8") !== content) {
    changed.push(relative(repoRoot, index));
    if (!check) writeFileSync(index, content, "utf8");
  }

  return { skipped: false, changed };
}

if (import.meta.url === pathToFileURL(process.argv[1] ?? "").href) {
  const { changed } = regenerateExamples();
  console.log(`Regenerated ${sources.length} committed example snapshots (${changed.length} changed).`);
}
